---
# Update apt and install dependencies
- name: Update apt and install dependencies
  apt:
    name:
      - unzip
      - curl
      - python3-pip
    state: present
    update_cache: yes

# Download AWS CLI
- name: Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

# Unzip AWS CLI
- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

# Install AWS CLI
- name: Install AWS CLI
  command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws

# Install latest kubectl
- name: Install latest kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
  register: kubectl_install
  changed_when: kubectl_install.rc == 0

  # Install Helm
- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  register: helm_install
  changed_when: helm_install.rc == 0




# Create AWS directory
- name: Create AWS directory
  file:
    path: /home/ubuntu/.aws
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'

# Configure AWS credentials
- name: Configure AWS credentials
  copy:
    dest: /home/ubuntu/.aws/credentials
    content: |
      [default]
      aws_access_key_id = {{ lookup('env', 'AWS_ACCESS_KEY') }}
      aws_secret_access_key = {{ lookup('env', 'AWS_SECRET_KEY') }}
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  no_log: true
  

# Configure AWS region
- name: Configure AWS config
  copy:
    dest: /home/ubuntu/.aws/config
    content: |
      [default]
      region = {{ aws_region }}
    owner: ubuntu
    group: ubuntu
    mode: '0600'

# Validate AWS credentials
- name: Validate AWS credentials
  become: false
  command:
    cmd: aws sts get-caller-identity
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  register: aws_identity
  changed_when: false

# Update kubeconfig for EKS
- name: Update kubeconfig for EKS
  become: false
  command:
    cmd: aws eks update-kubeconfig --name {{ eks_cluster_name }} --region {{ aws_region }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
    HOME: /home/ubuntu

# Verify EKS cluster access
- name: Verify EKS cluster access
  become: false
  command:
    cmd: kubectl get nodes
  environment:
    HOME: /home/ubuntu
  register: eks_nodes
  retries: "{{ max_retries }}"
  delay: "{{ retry_delay }}"
  until: eks_nodes.rc == 0
  changed_when: false

# Show EKS nodes
- name: Show EKS nodes
  debug:
    var: eks_nodes.stdout
