name: Application Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Deploy application"
        required: true
        default: "deploy"

jobs:
  setup-bastion-host:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install ansible boto3 botocore

      # Install AWS Ansible Collection
      - name: Install Ansible AWS Collection
        run: |
          ansible-galaxy collection install amazon.aws

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Setup SSH key
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.BASTION_SSH_KEY }}" > iips.pem
          chmod 600 iips.pem

      # Check AWS identity
      - name: Check AWS Credentials
        run: |
          aws sts get-caller-identity

      # Check Dynamic Inventory
      - name: Check Dynamic Inventory
        working-directory: infra/ansible
        run: |
          ansible-inventory \
            -i inventories/prod_aws_ec2.yml \
            --graph

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        working-directory: infra/ansible
        run: |
          ansible-playbook \
            -i inventories/prod_aws_ec2.yml \
            playbooks/check.yml \
            --private-key "$GITHUB_WORKSPACE/iips.pem" \
            --ssh-extra-args "-o StrictHostKeyChecking=no"