name: Application Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Deploy application"
        required: true
        default: "deploy"

jobs:
  setup-bastion-host:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install ansible boto3 botocore

      # Install AWS Ansible Collection
      - name: Install Ansible AWS Collection
        run: |
          ansible-galaxy collection install amazon.aws

      # Setup SSH key for bastion
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.BASTION_SSH_KEY }}" > secondaccount.pem
          chmod 600 secondaccount.pem

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      
      - name: Check Ansible Inventory
        run: |
          ansible-inventory -i infra/ansible/inventories/prod.yml --graph

      # Run playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook infra/ansible/playbooks/check.yml \
            -i infra/ansible/inventories/prod.yml \
            -u ubuntu \
            --private-key secondaccount.pem \
            --ssh-extra-args "-o StrictHostKeyChecking=no"