name: End to end mern stack devops project

on:
  push:
    branches: [ "main" ]
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    -  name: check out github code
       uses: actions/actions/checkout@v3
    -  name: message
       run: echo "github code checkout"

